In [7]:
import pandas as pd

In [8]:
# walk through folder merge and find all csv files

import os

csv_files = [f for f in os.listdir(".") if f.endswith(".csv")]

# read and concatenate all csv files
dataframes = [pd.read_csv(os.path.join("", f)) for f in csv_files]
merged_df = pd.merge(dataframes[0], dataframes[1], on="title")

merged_df.to_csv("merged_exports.csv", index=False)

In [2]:
screening_result = pd.read_csv('screening_result.csv', on_bad_lines="skip", encoding="ISO-8859-1")
screening_result.head()

,title,doi,inclusion,reasoning
0,AI and Human-AI Collaboration: Transforming Fi...,10.52783/jisem.v10i58s.12772,0,The article discusses AIâhuman collaboration...
1,Leveraging LLM-Based Agents for Intelligent Su...,10.48550/arXiv.2509.03811,1,"The paper focuses on supply chain planning, wh..."
2,Survey of LLM Agent Communication with MCP: A ...,10.48550/arXiv.2506.05364,0,The paper surveys LLMâbased multiâagent co...
3,Understanding agentic artificial intelligence:...,NaN,0,The work focuses on financial transformation a...
4,Deploying agentic artificial intelligence mode...,NaN,1,The paper focuses on **agentic AI models** app...

In [4]:
openalex_export_xpac_curated = pd.read_csv('openalex_export_xpac_curated.csv')
openalex_export_xpac_curated.rename({'ï»¿title': 'title'}, inplace=True)
openalex_export_xpac_curated.head()

,title,doi,type,duplicate,not_en,wrong_type,no_doi,fulltext_not_available,inclusion,inclusion_llm,cited_by_count
0,A Cognitive Digital Twin for Industry 5.0 Base...,10.1109/ICHMS65439.2025.11154278,conferencePaper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,A Comprehensive Evaluation of Contemporary ML-...,10.48550/ARXIV.2505.16952,preprint,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,A Comprehensive Survey of AI Agent Frameworks ...,10.20944/preprints202505.0971.v1,preprint,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,A Framework for Monte-Carlo Tree Search on CPU...,10.1145/3543622.3573177,conferencePaper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,A Generative AI-Powered System with LLM,NaN,bookSection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [6]:
# merge both dataframes on title column
final_merged_df = pd.merge(screening_result, openalex_export_xpac_curated, how="outer", on="title")

final_merged_df.to_csv("merged_export.csv", index=False)