In [23]:
import pandas as pd

In [24]:
screened_df = pd.read_csv("merge/26_09_25_first_screening_v2.csv", )
# load with compatible encoding
og_df = pd.read_csv("merge/openalex_export.csv", on_bad_lines="skip", encoding="ISO-8859-1")

In [25]:
screened_df.head()

,title,doi,inclusion,reasoning
0,Cognitive digital twin-based Internet of Robot...,10.24136/eq.3131,1,The title and fulltext of the paper explicitly...
1,Towards autonomous system: flexible modular pr...,10.48550/ARXIV.2304.14721,1,1) The article explicitly focuses on Large Lan...
2,SciAgents: Automating Scientific Discovery Thr...,10.1002/adma.202413523,1,"The article discusses a multi-agent system, Sc..."
3,A Large Language Model-based multi-agent manuf...,10.48550/ARXIV.2405.16887,1,The paper 'A Large Language Model-based multi-...
4,Automating alloy design and discovery with phy...,10.1073/pnas.2414074122,1,"The paper is excluded because, although it men..."

In [26]:
og_df.head()

,ï»¿id,doi,title,display_name,relevance_score,publication_year,publication_date,language,type,type_crossref,...,locations.source.type,locations.source,sustainable_development_goals.id,sustainable_development_goals.score,sustainable_development_goals.display_name,grants.funder,grants.funder_display_name,grants.award_id,counts_by_year.year,counts_by_year.cited_by_count
0,https://openalex.org/W4387567460,https://doi.org/10.1109/etfa54631.2023.10275362,Towards autonomous system: flexible modular pr...,Towards autonomous system: flexible modular pr...,67.65801,2023,09-12-23,en,article,proceedings-article,...,conference|repository,nan|nan,https://metadata.un.org/sdg/9,0.46,"Industry, innovation and infrastructure",https://openalex.org/F4320329143,Stiftung der Deutschen Wirtschaft,NaN,2025|2024,15.0000000
1,https://openalex.org/W4405104323,https://doi.org/10.1109/sdf63218.2024.10773919,A Hybrid AI Framework Integrating Ontology Lea...,A Hybrid AI Framework Integrating Ontology Lea...,64.673706,2024,11-25-24,en,article,proceedings-article,...,NaN,NaN,https://metadata.un.org/sdg/9,0.51,"Industry, innovation and infrastructure",NaN,NaN,NaN,2025,1
2,https://openalex.org/W4390824394,https://doi.org/10.1021/acsengineeringau.3c00058,Generative Retrieval-Augmented Ontologic Graph...,Generative Retrieval-Augmented Ontologic Graph...,41.557976,2024,01-12-24,en,article,journal-article,...,journal|repository|repository|repository,nan|nan|nan|nan,https://metadata.un.org/sdg/4,0.61,Quality education,https://openalex.org/F4320306114|https://opena...,U.S. Department of Agriculture|Massachusetts I...,2021-69012-35978|None|None|N00014-19-1-2375|N0...,2025|2024,16.0|16
3,https://openalex.org/W4402917435,https://doi.org/10.24136/eq.3131,Cognitive digital twin-based Internet of Robot...,Cognitive digital twin-based Internet of Robot...,37.387295,2024,09-27-24,en,article,journal-article,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,|Zdenk Caha|Roman Bla~ek|Erika Kovalová|Marek...,https://orcid.org/0000-0002-3422-6310|https://...,https://openalex.org/T10763|https://openalex.o...,Digital Transformation in Industry|Impact of A...,0.9712|0.963|0.9343,https://openalex.org/subfields/2209|https://op...,Industrial and Manufacturing Engineering|Manag...,https://openalex.org/fields/22|https://openale...,"Engineering|Decision Sciences|Business, Manage...",https://openalex.org/domains/3|https://openale...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN