In [1]:
import pandas as pd

In [8]:
# openalex and zotero difference comparison
df1 = pd.read_csv("openalex.csv", on_bad_lines="skip")
df2 = pd.read_csv("zotero.csv", on_bad_lines="skip")

# get columns title and doi
df1 = df1[['title', 'doi']]
df2.rename(columns={'Title': 'title', 'DOI': 'doi'}, inplace=True)
df2 = df2[['title', 'doi']]

# remove https://doi.org/ from doi column in both dataframes
df1['doi'] = df1['doi'].str.replace('https://doi.org/', '', regex=False)
# set all rows in doi column to lowercase
df1['doi'] = df1['doi'].str.lower()
df2['doi'] = df2['doi'].str.lower()

# concat df along title and doi columns
concat_df = pd.concat([df1, df2], ignore_index=True)
concat_df.drop_duplicates(inplace=True, keep=False, ignore_index=True)

concat_df

,title,doi
0,GraphMaster: Automated Graph Synthesis via LLM...,https://arxiv.org/abs/2504.00711
1,SymbionÃ¢ÂÂ¢ V2: Field-Coherent Intelligence ...,10.5281/zenodo.16808935
2,Understanding agentic artificial intelligence:...,10.70593/978-81-988918-1-5_3
3,Gala: Global LLM Agents for Text-to-Model Tran...,https://arxiv.org/abs/2509.08970
4,Training Small Reasoning LLMs with Cognitive P...,10.48550/arxiv.2504.09802
...,...,...
68,ENIGMA: An explainable digital twin security s...,10.1016/j.compind.2023.103961
69,Agentic AI-Driven Dynamic Resource Allocation ...,NaN
70,What to Share? A Preliminary Investigation int...,NaN
71,AI-Driven Industry 4.0 and Smart Infrastructure,NaN
72,An AI-based model for managing a smart seafood...,NaN

In [15]:
# zotero datasets only difference
df1 = pd.read_csv("seed.csv")
df2 = pd.read_csv("snowballing_depth1.csv")
df3 = pd.read_csv("snowballing_depth2.csv")
df4 = pd.read_csv("snowballing_depth3.csv")

# concat along title and doi columns
concat_df = pd.concat([df1, df2, df3], ignore_index=True)

concat_df

,Key,Item Type,Publication Year,Author,Title,Publication Title,ISBN,ISSN,DOI,Url,...,Programming Language,Version,System,Code,Code Number,Section,Session,Committee,History,Legislative Body
0,89F29DIR,conferencePaper,2025.0,"Lou, Shanhe; Tan, Runjia; Zhou, Mengchu; Lv, Chen",A Cognitive Digital Twin for Industry 5.0 Base...,2025 IEEE 5th International Conference on Huma...,979-8-3315-2164-6,NaN,10.1109/ICHMS65439.2025.11154278,https://ieeexplore.ieee.org/document/11154278/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,S7EC9NFN,preprint,2025.0,"Feng, Shengyu; Sun, Weiwei; Li, Shanda; Talwal...",A Comprehensive Evaluation of Contemporary ML-...,NaN,NaN,NaN,10.48550/ARXIV.2505.16952,https://arxiv.org/abs/2505.16952,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9B87LYFF,preprint,2025.0,"Joshi, Satyadhar",A Comprehensive Survey of AI Agent Frameworks ...,NaN,NaN,NaN,10.20944/preprints202505.0971.v1,https://www.preprints.org/manuscript/202505.09...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KDL985TW,conferencePaper,2023.0,"Meng, Yuan; Kannan, Rajgopal; Prasanna, Viktor",A Framework for Monte-Carlo Tree Search on CPU...,Proceedings of the 2023 ACM/SIGDA Internationa...,978-1-4503-9417-8,NaN,10.1145/3543622.3573177,https://dl.acm.org/doi/10.1145/3543622.3573177,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RB7JKQP3,bookSection,2025.0,"Lv, Meixuan; Chen, Yaru; Gao, Cong; Zheng, Xig...",A Generative AI-Powered System with LLM,Advances in Transdisciplinary Engineering,978-1-64368-614-1,NaN,NaN,https://ebooks.iospress.nl/doi/10.3233/ATDE250920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,4RME69UZ,bookSection,2023.0,"Chhotaray, Pravatnallini; Behera, Bikash Chand...",Enhancement of Manufacturing Sector Performanc...,Smart Technologies for Improved Performance of...,978-1-003-34662-3,NaN,NaN,https://www.taylorfrancis.com/books/9781003346...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,2VQZ3ZAK,journalArticle,2023.0,"Deshpande, Sourabh; Padalkar, Shailesh; Anand,...",IIoT based framework for data communication an...,Manufacturing Letters,NaN,22138463,10.1016/j.mfglet.2023.08.058,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,3TPYNJ9N,journalArticle,2023.0,"Durigan, Paulo De Tarso; Shiki, Sidney Bruce; ...",On the potential of low-cost instrumentation f...,The International Journal of Advanced Manufact...,NaN,"0268-3768, 1433-3015",10.1007/s00170-023-11946-5,https://link.springer.com/10.1007/s00170-023-1...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,YIP4ETYR,journalArticle,2024.0,"Da Silva, Agostinho; Cardoso, Antonio J. Marques",Co-Opetition and the Industrial Internet of Th...,Administrative Sciences,NaN,2076-3387,10.3390/admsci14060125,https://www.mdpi.com/2076-3387/14/6/125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,53A86K6W,preprint,2022.0,"Radford, Alec; Kim, Jong Wook; Xu, Tao; Brockm...",Robust Speech Recognition via Large-Scale Weak...,NaN,NaN,NaN,10.48550/ARXIV.2212.04356,https://arxiv.org/abs/2212.04356,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# get difference between dfs
df_diff = df4[df4['Title'].isin(concat_df['Title'])]
df_diff

,Key,Item Type,Publication Year,Author,Title,Publication Title,ISBN,ISSN,DOI,Url,...,Programming Language,Version,System,Code,Code Number,Section,Session,Committee,History,Legislative Body
31,2DAC67VV,journalArticle,2024,"Wang, Tian; Fan, Junming; Zheng, Pai",An LLM-based vision and language cobot navigat...,Journal of Manufacturing Systems,NaN,02786125,10.1016/j.jmsy.2024.04.020,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,YH7XBP67,journalArticle,2024,"Sun, Yicheng; Zhang, Qi; Bao, Jinsong; Lu, Yuq...",Empowering digital twins with large language m...,Journal of Manufacturing Systems,NaN,02786125,10.1016/j.jmsy.2024.02.015,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,74HIZXB4,conferencePaper,2022,"Du, Zhengxiao; Qian, Yujie; Liu, Xiao; Ding, M...",GLM: General Language Model Pretraining with A...,Proceedings of the 60th Annual Meeting of the ...,NaN,NaN,10.18653/v1/2022.acl-long.26,https://aclanthology.org/2022.acl-long.26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2IDILSWL,journalArticle,2024,"Pan, Shirui; Luo, Linhao; Wang, Yufei; Chen, C...",Unifying Large Language Models and Knowledge G...,IEEE Transactions on Knowledge and Data Engine...,NaN,"1041-4347, 1558-2191, 2326-3865",10.1109/TKDE.2024.3352100,https://ieeexplore.ieee.org/document/10387715/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,6P37JPXD,journalArticle,2023,"Xu, Zhaoguang; Dang, Yanzhong",Data-driven causal knowledge graph constructio...,International Journal of Production Research,NaN,"0020-7543, 1366-588X",10.1080/00207543.2022.2078748,https://www.tandfonline.com/doi/full/10.1080/0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,ZNNJXLDQ,journalArticle,2024,"Chen, Zheyuan; Wan, Yuwei; Liu, Ying; Valera-M...",A knowledge graph-supported information fusion...,Information Fusion,NaN,15662535,10.1016/j.inffus.2023.101985,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,76MP3EWI,preprint,2023,"Touvron, Hugo; Lavril, Thibaut; Izacard, Gauti...",LLaMA: Open and Efficient Foundation Language ...,NaN,NaN,NaN,10.48550/ARXIV.2302.13971,https://arxiv.org/abs/2302.13971,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,9YWIRAHP,journalArticle,2025,"Mustapha, K.B.",A survey of emerging applications of large lan...,Advanced Engineering Informatics,NaN,14740346,10.1016/j.aei.2024.103066,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,KH3B7FAD,journalArticle,2024,"Wu, Tao; Li, Jie; Bao, Jinsong; Liu, Qiang",ProcessCarbonAgent: A large language models-em...,Journal of Manufacturing Systems,NaN,02786125,10.1016/j.jmsy.2024.08.008,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,DBEQ4ZM3,journalArticle,2025,"Ma, Yanjun; Wu, Tao; Zhou, Bin; Liang, Xiaoyan...",Enhancing Bottleneck Analysis in Ship Manufact...,Machines,NaN,2075-1702,10.3390/machines13030224,https://www.mdpi.com/2075-1702/13/3/224,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,ZDLYFTNN,journalArticle,2025,"Xiong, Xirui; Cai, Hongming; Yu, Han; Shen, Bi...",DR-RAG: Domain-Rule-based Retrieval-Augmented ...,Advanced Engineering Informatics,NaN,14740346,10.1016/j.aei.2025.103688,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,ZET7UT9D,journalArticle,2025,"Wang, Ji; Zhuang, Weibin; Liu, Tianyuan; Bao, ...",Analysis of causes of welding defects in bridg...,Journal of Industrial Information Integration,NaN,2452414X,10.1016/j.jii.2025.100954,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,9SLT528M,journalArticle,2026,"Shi, Dachuan; Meyer, Olga; Fan, Zhi; Wang, Hao...",Cognitive digital twins for capability matchin...,Robotics and Computer-Integrated Manufacturing,NaN,07365845,10.1016/j.rcim.2025.103105,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,YX2F7MZR,journalArticle,2025,"Chen, Jianguo; Wang, Yu; Guo, Dongxu; Liu, Zhi...",Advancing battery research through large langu...,The Innovation,NaN,26666758,10.1016/j.xinn.2025.101091,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,L7RNQCC3,journalArticle,2025,"Moenks, Norbert; Penava, Pascal; Buettner, Ric...",A Systematic Literature Review of Large Langua...,IEEE Access,NaN,2169-3536,10.1109/ACCESS.2025.3608650,https://ieeexplore.ieee.org/document/11155093/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,2TSSAV7C,journalArticle,2025,"Lee, Junhyeong; Kim, Joon-Young; Kim, Heekyu; ...",IM-Chat: A multi-agent LLM framework integrati...,Journal of Manufacturing Systems,NaN,02786125,10.1016/j.jmsy.2025.11.007,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,QXI5ZAQH,journalArticle,2025,"Cha, Minhyeok; Yoon, Sang-il; Kim, Seongrae; K...",Large Language Model-Based Autonomous Agent fo...,Machines,NaN,2075-1702,10.3390/machines13090831,https://www.mdpi.com/2075-1702/13/9/831,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,ULB5JJ7R,journalArticle,2024,"Xu, Shengyang; Wei, Yao; Zheng, Pai; Zhang, Ji...",LLM enabled generative collaborative design in...,Journal of Manufacturing Systems,NaN,02786125,10.1016/j.jmsy.2024.04.030,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,B7JDYAWI,journalArticle,2025,"Gautam, Anuj; Aryal, Manish Raj; Deshpande, So...",IIoT-enabled digital twin for legacy and smart...,Journal of Manufacturing Systems,NaN,02786125,10.1016/j.jmsy.2025.03.022,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,5Z9YXDIA,journalArticle,2025,"Yao, Qi; Fang, Fang; Chen, Yuanye; Liu, Jizhen...",AI Large Models for Power System: A Survey and...,IET Smart Energy Systems,NaN,"3065-9647, 3065-9655",10.1049/ses2.70000,https://ietresearch.onlinelibrary.wiley.com/do...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,8UBXSZQG,journalArticle,2025,"Ziemba, Paweł; Majewski, Filip",Using the Large Language Model ChatGPT to Supp...,Sustainability,NaN,2071-1050,10.3390/su17167520,https://www.mdpi.com/2071-1050/17/16/7520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,4GYCRNL2,journalArticle,2026,"Bian, Chong; Duan, Zhiyu; Li, Daoyi; Yang, Shu...",Joint state-of-charge and state-of-health esti...,Reliability Engineering & System Safety,NaN,09518320,10.1016/j.ress.2025.111872,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,4WNUN6PS,journalArticle,2024,"Wang, Lei; Ma, Chen; Feng, Xueyang; Zhang, Zey...",A survey on large language model based autonom...,Frontiers of Computer Science,NaN,"2095-2228, 2095-2236",10.1007/s11704-024-40231-1,https://link.springer.com/10.1007/s11704-024-4...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,IVPAJDV5,conferencePaper,2024,"Chen, Yinfang; Xie, Huaibing; Ma, Minghua; Kan...",Automatic Root Cause Analysis via Large Langua...,Proceedings of the Nineteenth European Confere...,979-8-4007-0437-6,NaN,10.1145/3627703.3629553,https://dl.acm.org/doi/10.1145/3627703.3629553,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,Q847PG7P,journalArticle,2025,"Ren, Yinwang; Liu, Yangyang; Ji, Tang; Xu, Xun",AI Agents and Agentic AI–navigating a plethora...,Journal of Manufacturing Systems,NaN,02786125,10.1016/j.jmsy.2025.08.017,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,ZABBX4VY,journalArticle,2025,"Yuan, Zhaolin; Li, Ming; Liu, Chang; Han, Fang...",Chat with MES: LLM-driven user interface for m...,Journal of Manufacturing Systems,NaN,02786125,10.1016/j.jmsy.2025.02.008,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251,AD2GNU9W,journalArticle,2025,"Xiaorui, Liu; Yuhao, Zhang; Leiqi, Wang; Lexia...",LLMs driven fusion AI-AD system for mechanical...,Advanced Engineering Informatics,NaN,14740346,10.1016/j.aei.2025.103745,https://linkinghub.elsevier.com/retrieve/pii/S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_diff.to_csv("difference.csv")